PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = Beta

ifeq ($(ORION_VERSION_APPEND_TIME_OF_DAY),true)
    ORION_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    ORION_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set LINEAGE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef ORION_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "LINEAGE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^ORION_||g')
        ORION_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(ORION_BUILDTYPE)),)
    ORION_BUILDTYPE := UNOFFICIAL
    ORION_EXTRAVERSION :=
endif

ifeq ($(ORION_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        ORION_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

ORION_VERSION_SUFFIX := $(ORION_BUILD_DATE)-$(ORION_BUILDTYPE)$(ORION_EXTRAVERSION)-$(ORION_BUILD)

# Internal version
ORION_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(ORION_VERSION_SUFFIX)

# Display version
ORION_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(ORION_VERSION_SUFFIX)

ORION_DATE_YEAR := $(shell date -u +%Y)
ORION_DATE_MONTH := $(shell date -u +%m)
ORION_DATE_DAY := $(shell date -u +%d)
ORION_DATE_HOUR := $(shell date -u +%H)
ORION_DATE_MINUTE := $(shell date -u +%M)
ORION_BUILD_DATE_UTC := $(shell date -d '$(ORION_DATE_YEAR)-$(ORION_DATE_MONTH)-$(ORION_DATE_DAY) $(ORION_DATE_HOUR):$(ORION_DATE_MINUTE) UTC' +%s)
ORION_BUILD_DATE := $(ORION_DATE_YEAR)$(ORION_DATE_MONTH)$(ORION_DATE_DAY)-$(ORION_DATE_HOUR)$(ORION_DATE_MINUTE)